spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schooldb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kucu
    password: kucu

mybatis:
  mapper-locations: classpath:resources/mapper/**/*.xml
  config-location: classpath:mapper/mapper-config.xml

