spring:
  datasource:
    url: jdbc:mysql://222.112.124.237:3306/kbjcompanydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kimbaekjung
    password: 1q2w3e4r!@

mybatis:
  mapper-locations: classpath:resources/mapper/*.xml
  config-location: classpath:mapper/mapper-config.xml